mail:
  smtp: smtp.gmail.com
  sender: xxx@gmail.com
  recipient: xxxx@gmail.com
  login: xxxx
  password: yyyyyy
elastic:
  nodes: ["http://x.x.x.x:9200"]
  apiid: 
  apikey:
  index: "prix-test"
masto:
  api_base_url: https://piaille.org
  login: xxx@xxx.com
  password: yyyy
discord:
  vtt: <web hook url>
  cargo: <web hook url>
  default: <web hook url>
level: DEBUG
tosurvey:
  #aliexpress-minipc: https://fr.aliexpress.com/af/mini-pc.html?trafficChannel=af&SearchText=mini+pc&ltype=affiliate&SortType=default&page=1&CatId=0
  # crash du à la suppression du résultat "crawler"
  # pour info : https://github.com/sudheer-ranga/aliexpress-product-scraper
  cyclable-veloelec: https://www.cyclable.com/13-velo-electrique?p=1
  cyclable-cargo: https://www.cyclable.com/963-velo-cargo?p=1
  cyclable-graveltreck: https://www.cyclable.com/1467-velos-gravel-trekking?p=1
  cyclable-pliant: https://www.cyclable.com/14-velo-pliant?p=1
  cyclable-muscu: https://www.cyclable.com/1468-velo-musculaire?p=1
  cyclable-enfants: https://www.cyclable.com/27-velo-et-enfant?p=1
  decathlon-veloelec: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-electriques/_/N-18yx854Z1o76joc?from=0&size=40
  decathlon-veloville: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-de-ville/c2-velo-de-ville/_/N-2ub1rzZ1o76joc?from=0&size=40
  decathlon-vtt: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-tout-terrain-vtt/c2-velos-vtt/_/N-pjowgaZ1o76joc?from=0&size=40
  decathlon-vtc: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-tout-chemin-vtc/c2-velos-vtc/_/N-bjwqeyZ1o76joc?from=0&size=40
  decathlon-veloroute: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-route/c2-velos/_/N-nkqv8sZ1o76joc?from=0&size=40
  decathlon-enfants: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-enfant/c2-velos-enfants/_/N-esjxunZ1o76joc?from=0&size=40
  decathlon-velofemme: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-femme/_/N-8jve0sZ1o76joc?from=0&size=40
  decathlon-velohomme: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-homme/_/N-1e3g48jZ1o76joc?from=0&size=40
  decathlon-velobmx: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-bmx/_/N-640gwmZ1o76joc?from=0&size=40
  decathlon-velopliant: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-intermodal/c2-velos-pliants/_/N-g3510qZ1o76joc?from=0&size=40
  decathlon-velocarbon: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-carbone/_/N-1dh7k4hZ1o76joc?from=0&size=40
  decathlon-occass: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c3-velos-occasion/_/N-cm4rh6Z1o76joc?from=0&size=40
  probikeshop-vtc: https://www.probikeshop.fr/velo-urbain/velos-urbains-vtc-c9223.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-trecking: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-de-voyage-c9891.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-ville: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-de-ville-c9220.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-hollandais: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-hollandais-c12047.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-pliant: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-pliants-c9226.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-fixie: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-fixie-c9224.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vtcelec: https://www.probikeshop.fr/velo-urbain/velos-urbains-lectriques-vtc-lectriques-c20973.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-treckelec: https://www.probikeshop.fr/velo-urbain/velos-urbains-lectriques-velos-de-randonnee-lectriques-c20975.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-villeelec: https://www.probikeshop.fr/velo-urbain/velos-urbains-lectriques-velos-de-ville-lectriques-c20977.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-cargoelec: https://www.probikeshop.fr/velo-urbain/velos-urbains-lectriques-velos-cargo-lectriques-c20979.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-bmx: https://www.probikeshop.fr/bmx/bmx-street-dirt-bmx-complets-c3257.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttsuspen: https://www.probikeshop.fr/vtt/velos-complets-vtt-tout-suspendus-c10967.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttssemi: https://www.probikeshop.fr/vtt/velos-complets-vtt-semi-rigides-c10966.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttsuspen: https://www.probikeshop.fr/vtt/velos-complets-vtt-loisirs-c13330.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttelec: https://www.probikeshop.fr/electrique/velos-electriques-vtt-electriques-hommes-c13674.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttenfant: https://www.probikeshop.fr/vtt/velos-complets-vtt-enfants-c10970.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-vttsfemme: https://www.probikeshop.fr/vtt/velos-complets-vtt-femmes-c10968.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-course: https://www.probikeshop.fr/route/velos-complets-velos-de-course-c10084.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-gravel: https://www.probikeshop.fr/route/velos-complets-velos-de-gravel-c10087.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-cyclocross: https://www.probikeshop.fr/route/velos-complets-velos-de-cyclocross-c10086.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-contremontre: https://www.probikeshop.fr/route/velos-complets-velos-de-contre-la-montre-c10085.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-piste: https://www.probikeshop.fr/route/velos-complets-velos-de-piste-c10088.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-coursefemme: https://www.probikeshop.fr/route/velos-complets-velos-femmes-c11712.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  probikeshop-courseelec: https://www.probikeshop.fr/electrique/velos-electriques-velos-de-route-electriques-c13707.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  bikester-vtt: https://www.bikester.fr/velos/vtt/?page=1&sz=48
  bikester-treck: https://www.bikester.fr/velos/velos-de-trekking/?page=1&sz=48
  bikester-route: https://www.bikester.fr/velos/velos-de-route/?page=1&sz=48
  bikester-ville: https://www.bikester.fr/velos/velos-de-ville/?page=1&sz=48
  bikester-elec: https://www.bikester.fr/velos/velos-electriques/?page=1&sz=48
  bikester-enfant: https://www.bikester.fr/velos/velos-enfant-ado/?page=1&sz=48
  ###### to adapt/enlarge
  alltricks-vtt: https://www.alltricks.fr/C-40415-velos
  alltricks-elec: https://www.alltricks.fr/C-834161-velos-de-route-electriques
  alltricks-treck: https://www.alltricks.fr/C-45873-velos-de-voyage-randonnee
  ###### old
  #probikeshop-trecking: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-de-voyage-c9891.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  #cyclable-treck: https://www.cyclable.com/16-velo-trekking?p=1
  #decathlon-cargo: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-de-ville/c2-velo-de-ville/nature-velo-cargo/_/N-2ub1rzZ8o5chjZ1o76joc
  #decathlon-sailing: https://www.decathlon.fr/search?Ntt=tribord+sailing+500
  #decathlon-roues: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c4-roues-velo/_/N-1xj22fxZ1ubzga0ZvhmwjpZ1cgl8hyZnbzutd