mail:
  smtp: smtp.gmail.com
  sender: xxx@gmail.com
  recipient: xxxx@gmail.com
  login: xxxx
  password: yyyyyy
elastic:
  nodes: ["http://x.x.x.x:9200"]
  apiid: 
  apikey:
  index: "prix-test"
masto:
  api_base_url: https://piaille.org
  login: xxx@xxx.com
  password: yyyy
level: DEBUG
tosurvey:
  aliexpress-minipc: https://fr.aliexpress.com/af/mini-pc.html?trafficChannel=af&SearchText=mini+pc&ltype=affiliate&SortType=default&page=1&CatId=0
  alltricks-elec: https://www.alltricks.fr/C-834161-velos-de-route-electriques
  alltricks-treck: https://www.alltricks.fr/C-45873-velos-de-voyage-randonnee
  decathlon-sailing: https://www.decathlon.fr/search?Ntt=tribord+sailing+500
  decathlon-cargo: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-de-ville/c2-velo-de-ville/nature-velo-cargo/_/N-2ub1rzZ8o5chjZ1o76joc
  decathlon-roues: https://www.decathlon.fr/browse/c0-tous-les-sports/c1-velo-cyclisme/c4-roues-velo/_/N-1xj22fxZ1ubzga0ZvhmwjpZ1cgl8hyZnbzutd
  probikeshop-trecking: https://www.probikeshop.fr/velo-urbain/velos-urbains-velos-de-voyage-c9891.html?t=0&manId=0&catId=9891&page=1&display_mode=3&sales=false
  bikester-treck-electrique: https://www.bikester.fr/velos/velos-electriques/velos-de-trekking-electriques/?page=1&sz=48
  bikester-treck-homme: https://www.bikester.fr/velos/velos-de-trekking/velos-de-trekking-homme/?page=1&sz=48
  bikester-treck-femme: https://www.bikester.fr/velos/velos-de-trekking/velos-de-trekking-femme/?page=1&sz=48