bikester.fr:
  name_tree: "div,class,product-tile-inner" #div,id,data-uv-item ??
  price: "span,class,price-standard"
  price_sale: "span,class,price-sales"
  name: "div,class,product-name"
  marque: "div,class,cyc-typo_subheader"
  variations: "span,class,variations"
  number_articles: "span,class,cyc-typo_subheader"
decathlon.fr:
  name_tree: "script,id,__dkt"
probikeshop.fr:
  name_tree: "div,class,product row"
  price: "span,class,product_price" #span class="product_price"
  price_sale: ""
  name: "span,class,product_title"
  marque: "" #"span,itemprop,name"
  variations: "span,class,productInfoComplementary_stock"
  number_articles: ""
alltricks.fr:
  name_tree: "div,class,alltricks-Product--3columns" #"div,class,alltricks-Pager__item"
  price: "span,class,alltricks-Product-price" #"span,data-price-product-obj,"
  price_sale: ""
  name: "a,class,alltricks-Product-description" #"a,class,alltricks-Product-description"
  marque: "strong,class,alltricks-Product-brandLabel"
  variations: "p,class,alltricks-ChildSelector-customOptionLabel" #"div,class,alltricks-ChildSelector-customOptions-group"
  number_articles: "" #"div,class,alltricks-ProductListingHeader__item--left"
fr.aliexpress.com:
  name_tree: "script,type,text/javascript"
  #name_tree: "a,class,31q8B _2f4Ho"
  #price: "div,class_3gurs _37W_B"
  #price_sale: ""
  #name: "h1,class,_3y9Q1"
  #marque: ""
  #variations: ""
  #number_articles: ""