bikester.fr:
  name_tree: "div,class,js-product-tile-lazyload" #"div,class,product-tile-inner"
  #<div id="4933cef7f431080065fcb006af" data-productid="G1520768" data-masterid="M1033235" class="js-product-tile-lazyload gtm-producttile product-tile  uv-item   product-tile--notavailable" data-uv-item="{&quot;id&quot;:&quot;1520768&quot;,&quot;unit_sale_price&quot;:3819}" data-gtm-productdata="{&quot;name&quot;:&quot;Cube Kathmandu Hybrid EXC 750 Entrée basse, vert&quot;,&quot;id&quot;:&quot;1520768&quot;,&quot;brand&quot;:&quot;Cube&quot;,&quot;price&quot;:3182.5,&quot;dimension42&quot;:&quot;Unavailable&quot;,&quot;dimension43&quot;:&quot;vert&quot;,&quot;dimension50&quot;:&quot;false&quot;,&quot;metric4&quot;:3819,&quot;metric7&quot;:0,&quot;metric8&quot;:1,&quot;variant&quot;:&quot;46cm | XS (28\&quot;)&quot;,&quot;dimension53&quot;:&quot;46cm | XS (28\&quot;)&quot;}">
  price: "span,class,price-standard"
  price_sale: "span,class,price-sales"
  name: "div,class,product-name"
  marque: "div,class,cyc-typo_subheader"
  variations: "span,class,variations"
  number_articles: "span,class,cyc-typo_subheader"
  #id: "div,class,js-product-tile-lazyload" #"div,data-gtm-productdata" #"div,class,grid-tile"
  number_pages: ""
decathlon.fr:
  name_tree: "script,id,__dkt"
probikeshop.fr:
  name_tree: "div,class,product row"
  price: "span,class,product_price" #span class="product_price"
  price_sale: ""
  name: "span,class,product_title"
  marque: "" #"span,itemprop,name"
  variations: "span,class,productInfoComplementary_stock"
  #number_articles: "span,class,listingHeadSubtitle_nb"
  number_articles: "input,class,nbProducts"
  number_pages: ""
alltricks.fr:
  name_tree: "div,class,alltricks-Product--3columns" #"div,class,alltricks-Pager__item"
  price: "span,class,alltricks-Product-price" #"span,data-price-product-obj,"
  price_sale: ""
  name: "a,class,alltricks-Product-description" #"a,class,alltricks-Product-description"
  marque: "strong,class,alltricks-Product-brandLabel"
  variations: "p,class,alltricks-ChildSelector-customOptionLabel" #"div,class,alltricks-ChildSelector-customOptions-group"
  number_articles: "" #"div,class,alltricks-ProductListingHeader__item--left"
  number_pages: ""
cyclable.com:
  name_tree: "li,class,category" #"ul,id,product_list"
  price: "span,class,price"
  price_sale: ""
  name: "h3,class,product-item-title"
  marque: "div,class,d-none" #"span,itemprop,name"
  variations: ""
  number_articles: ""
  number_pages: "div,id,pagination_bottom,li,span"
  #<meta itemprop="productID" content="14889">
culturevelo.com:
  name_tree: "article,class,dalle" #"div,id,LISTE"
  price: "div,class,dalle-prix"
  price_sale: ""
  name: "h4"
  marque: "h3"
  variations: "span,class,dispo"
  number_articles: "" #"div,class,count"
  number_pages: "" #381/27=14,11 => 15 ?
intersport.fr:
  name_tree: "div,id,productList" #"div,class,product-grid__card"
  price: "span,class,product-card__price"
  price_sale: "span,class,product-card__price--alert"
  name: "a,class,product-url"
  marque: "div,class,product-card__infos"
  variations: ""
  number_articles: ""
  number_pages: "" 
fr.aliexpress.com:
  name_tree: "script,type,text/javascript"
  #name_tree: "a,class,31q8B _2f4Ho"
  #price: "div,class_3gurs _37W_B"
  #price_sale: ""
  #name: "h1,class,_3y9Q1"
  #marque: ""
  #variations: ""
  #number_articles: ""
deporvillage.fr:
  name_tree: "script,id,__NEXT_DATA__"
  #name_tree: "div,class,ProductList_product-list" #__piQTi"
  #price: "div,class,ProductItem_price-special" # __Jh_z1""
  #price_sale: "div,class,ProductItem_product-item-price" #__M067y"
  #name: "div,class,ProductItem_product-item-name" #__W2by3"
  #marque: ""
  #variations: ""div,class,ProductItemList_product-item-bottom" #__5dwVG"
  #number_articles: "span,class,ProductList_total-items" #__5LnB7"
  #number_pages: ""
  #picture: "picture,img,src"
  name_tree2: "props,pageProps,model,items"
  number_pages: ""
  number_articles: "props,pageProps,model,pagination,itemsCount"
  brandlist: "props,pageProps,model,filters"
  id: "id"
  marque_id: "brand"
  #     retrouvé le nom :       filters -> "id":66, "type":"checkbox", "label":"Marques", "options" -> id":1738, "label":"BH Bikes",
  name: "title"
  url: "url"
  image: "gallery,images"
  price: "defaultVariant,price,pvp"
  price_sale: "defaultVariant,price,price"
  variations: "variants,items,name" # : stockLabel (FULLSTOCK ?)
bike24.fr:
  name_tree: "div,class,product-tile__container"
  price: "p,class,price__value"
  price_sale: ""
  name: "div,class,product-tile__title"
  marque: "p,class,product-tile__brand product-tile__text"
  variations: "div,class,delivery-message delivery-message--success delivery-message--large product-tile__delivery-message-wrapper"
  number_articles: "" #"div,class,product-sorting-bar__offers"
  number_pages: ""
  #id: "div,data-product,id"
  #url: "a,class,product-tile__anchor"